steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/jonjohnson-test/sstp-hackathon/frontend:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-docker.pkg.dev/jonjohnson-test/sstp-hackathon/frontend:latest']
  # This is racy, but imagine it were built into docker.
  - name: 'gcr.io/go-containerregistry/gcrane:debug'
    entrypoint: "/busybox/sh"
    args:
    - '-c'
    - |-
      gcrane mutate us-docker.pkg.dev/jonjohnson-test/sstp-hackathon/frontend:latest \
        -a "org.opencontainers.image.base.name=us-docker.pkg.dev/jonjohnson-test/sstp-hackathon/nginx:latest" \
        -a "org.opencontainers.image.base.digest=$(gcrane digest us-docker.pkg.dev/jonjohnson-test/sstp-hackathon/nginx:latest)"
